AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  process-visitors

  Sample SAM Template for process-visitors

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ProcessVisitorsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: process-visitors/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: arn:aws:iam::586914838657:role/service-role/AWSLambdaRekognitionRole
      Events:
        PhotoDrop:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket # bucket must be created in the same template
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: VisitorFaces/

  SrcBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: process-visitors-bucket

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProcessVisitorsFunction:
    Description: "ProcessVisitors Lambda Function ARN"
    Value: !GetAtt ProcessVisitorsFunction.Arn

